// configure DE settings for asciidoc
// asciidoc settings for DE (German)
// ==================================
// toc-title definition MUST follow document title without blank line!
= Dokumentation zur Materialsammlung (Gruppe: Material2)
:toc:
:toc-title: Inhaltsverzeichnis

// enable table-of-contents
:toc:

:caution-caption: Achtung
:important-caption: Wichtig
:note-caption: Hinweis
:tip-caption: Tip
:warning-caption: Warnung

:appendix-caption: Anhang
:example-caption: Beispiel
:figure-caption: Abbildung
:table-caption: Tabelle

// where are images located?
:imagesdir: documentation/images



:homepage: http://arc42.org
:keywords: software-architecture, documentation, template, arc42
:numbered!:

**Über arc42**

[role="lead"]
arc42, das Template zur Dokumentation von Software- und Systemarchitekturen.

Erstellt von Dr. Gernot Starke, Dr. Peter Hruschka und Mitwirkenden.

Template Revision: 7.0 DE (asciidoc-based), January 2017

(C) We acknowledge that this document uses material from the arc42 architecture template, http://www.arc42.de.
Created by Dr. Peter Hruschka & Dr. Gernot Starke.


// horizontal line
***
// numbering from here on
:numbered:

<<<<
// 1. Anforderungen und Ziele
[[section-introduction-and-goals]]
==  Problembeschreibung

Die größten Probleme in der Implementierung der Materialsammlung sind zu Zeit, dass wir einserseits das
erstellte Datenbankmodell in unserer Anwendung in Spring Data JDBC modellieren müssen, dies wird dadurch erschwert, dass
wir die m:n-Beziehungen unseres Datenbankmodels aufwendig implementieren müssen.

Der obere Umstand ist ebenso problematisch, da es Bedingt, dass die Implementierung der Geschäftslogik darunter leidet.

Auch ist es momentan schwierig eine "CI-freundliche" Implementierung von MinIO zu finden, die keine Fehlermeldung
in GitHub Actions übergibt.

==	Einführung und Ziele
Unser Ziel ist es eine schnelle, effeziente und benutzerfreundliche Materialsammlung zu entwicklen,
die dazu dient Vorlesungsinhalte und Lerngruppeninhalte zur Verfügung zu stellen.

Der Weg von einer Materialsammlungsansicht bis zur gewollten Datei soll hierbei nicht mehr als 5 Klicks
benötigen.

Uploadberechtigungen sollen gesetzt werden.

Die Benutzerschnittstelle soll dem gegebenen Styleguide entsprechen und übersichtlich sein.

Dateinen sollen mit tag versehen sein. Diese sollen einerseits aus voreingesellten Tags wählbar sein
andererseits sollen auch eigene Tags ersetllt werden sollen.

Es soll möglich gemacht werden Dateien zeitgesteuert für Studenten zugreifbar zu machen.

Das Suchen in den benötigten Datenbanken soll schnell realisiert werden.

Das Suchen innerhalb der GUI soll nach Tags, Daten, Dateinamen, Gruppenname, Dateiart, Dateigröße, Uploader.

Schnittstellen zum Zugriff auf Materialsammlungen für andere Module.

=== Aufgabenstellung

Folgende Aufgaben gilt es zu meistern:

- Aufgaben der Persisitenzschicht:

1. Es muss mit dem Team, das für die Gruppeneinteilung zuständig ist, sowohl eine Schnittstelle für den Zugriff auf die
von uns gebrauchten Daten wie z.B die Gruppenzugehörigket von Benutzern definiert als auch ein Protokoll zum übermitteln
und aktuallisieren eben dieser vereinbart werden. Für letzteres steht die Frage im Hintergrund ob die Aktuallisierung
in zeitlichen Intervallen oder nach bestimmten Triggern erfolgen soll.

2. Die Beziehung zwischen Benutzern, Gruppen und Dateien muss in einem ER-Diagramm festgehalten und in einem Datenbankschema
realisiert werden. Die Tabellen sollen die entstehenden Abhängigkeiten vollständig darstellen und aus den in
Punkt 1 übermittleten Daten gebildet werden können.

3. Das in Punkt 3 genannte Datenbankschema muss durch passende DTOs in der Anwendung abgebildet werden. Die Beziehungen der
einzelnen Entitäten im Datenbankschema muss passend in den DTOs abgebildet werden.

4. Es sollen den Entitäten des Datenbankschemas entsprechende Repositorys implementiert werden.

- Aufgaben der GUI:

1. *Startseite* : Gibt eine Einleitung in unsere System und erklärt den Umgang damit.

2. *Dateiübersicht* : Zeigt die zum Download verfügbaren Dateien einer Gruppe an.

3. *Suche* : Eine Seite fürs Suchen und Filtern der Dateien, wo die Such parameter mit einem PostMapping an die Businesslogic weiter-
gegeben wird.

4. *Hochladen* : Eine Seite fürs hochladen der Dateien. Hochladen dürfen Professoren und User, die in ihrer Lerngruppe die Berechtigung haben.

5. Eine Schnittstelle, für das Lernportfolio, wahrscheinlich mit Hilfe von Transklusion teile unserer Dateiübersicht.



=== Qualitätsziele

- Wartbarkeit

- Modifizierbarkeit

=== Stakeholder

[cols="1,1" options="header"]
|===
|Rolle |Erwartungshaltung
| Professoren | Einfache und übersichtliche Verwendung, zuverlässig, schnell
| Studierende | Übersichtlich, felxibel, erreichbar
| Fachbereich Informatik | wartbar, stabil, modifizierbar, sicher
|===


<<<<
// 2. Randbedingungen
[[section-architecture-constraints]]
== Randbedingungen




<<<<
// 3. Kontextabgrenzung
[[section-system-scope-and-context]]
== Kontextabgrenzung

=== Fachlicher Kontext

**<Diagramm und/oder Tabelle>**

**<optional: Erläuterung der externen fachlichen Schnittstellen>**

=== Technischer Kontext

**<Diagramm oder Tabelle>**

**<optional: Erläuterung der externen technischen Schnittstellen>**

**<Mapping fachliche auf technische Schnittstellen>**

<<<<
// 4. Lösungsstrategie
[[section-solution-strategy]]
== Lösungsstrategie



<<<<
// 5. Bausteinsicht
[[section-building-block-view]]
== Bausteinsicht

=== Whitebox Gesamtsystem

_**<Übersichtsdiagramm>**_

Begründung:: _<Erläuternder Text>_

Enthaltene Bausteine:: _<Beschreibung der enthaltenen Bausteine (Blackboxen)>_

Wichtige Schnittstellen:: _<Beschreibung wichtiger Schnittstellen>_

==== <Name Blackbox 1>

_<Zweck/Verantwortung>_

_<Schnittstelle(n)>_

_<(Optional) Qualitäts-/Leistungsmerkmale>_

_<(Optional) Ablageort/Datei(en)>_

_<(Optional) Erfüllte Anforderungen>_

_<(optional) Offene Punkte/Probleme/Risiken>_

==== <Name Blackbox 2>

_<Blackbox-Template>_

==== <Name Blackbox n>

_<Blackbox-Template>_

==== <Name Schnittstelle 1>

...

==== <Name Schnittstelle m>

=== Ebene 2

==== Whitebox _<Baustein 1>_

_<Whitebox-Template>_

==== Whitebox _<Baustein 2>_

_<Whitebox-Template>_

...

==== Whitebox _<Baustein m>_

_<Whitebox-Template>_

=== Ebene 3

==== Whitebox <_Baustein x.1_>

_<Whitebox-Template>_

==== Whitebox <_Baustein x.2_>

_<Whitebox-Template>_

==== Whitebox <_Baustein y.1_>

_<Whitebox-Template>_

<<<<
// 6. Laufzeitsicht
[[section-runtime-view]]
== Laufzeitsicht

=== _<Bezeichnung Laufzeitszenario 1>_

* <hier Laufzeitdiagramm oder Ablaufbeschreibung einfügen>
* <hier Besonderheiten bei dem Zusammenspiel der Bausteine in diesem Szenario erläutern>

=== _<Bezeichnung Laufzeitszenario 2>_

...

=== _<Bezeichnung Laufzeitszenario n>_

...

<<<<
// 7. Verteilungssicht
[[section-deployment-view]]
== Verteilungssicht

=== Infrastruktur Ebene 1

_**<Übersichtsdiagramm>**_

Begründung:: _<Erläuternder Text>_

Qualitäts- und/oder Leistungsmerkmale:: _<Erläuternder Text>_

Zuordnung von Bausteinen zu Infrastruktur:: _<Beschreibung der Zuordnung>_

=== Infrastruktur Ebene 2

==== _<Infrastrukturelement 1>_

_<Diagramm + Erläuterungen>_

==== _<Infrastrukturelement 2>_

_<Diagramm + Erläuterungen>_

...

==== _<Infrastrukturelement n>_

_<Diagramm + Erläuterungen>_

<<<<
// 8. Querschnittliche Konzepte
[[section-concepts]]
== Querschnittliche Konzepte

=== _<Konzept 1>_

_<Erklärung>_

=== _<Konzept 2>_

_<Erklärung>_

...

=== _<Konzept n>_

_<Erklärung>_

<<<<
// 9. Entscheidungen
[[section-design-decisions]]
== Entwurfsentscheidungen



<<<<
// 10. Qualität...
[[section-quality-scenarios]]
== Qualitätsanforderungen

=== Qualitätsbaum

=== Qualitätsszenarien



<<<<
// 11. Risiken
[[section-technical-risks]]
== Risiken und technische Schulden




<<<<
// 12. Glossar
[[section-glossary]]
== Glossar

[cols="1,2" options="header"]
|===
|Begriff
|Definition

|_<Begriff-1>_
|_<Definition-1>_


|_<Begriff-2_
|_<Definition-2>_
|===
