= MOPS: Materialsammlung 2

== Übersicht

Die hier implementierte Materialsammlung ist auf einer Schichtarchitektur
aufgebaut und soll den Benutzern eine schnelle, effektive und übersichtliche
Suche und angenehmen Zugriff auf ihre digitalen Lehrmaterialien erlauben.

== Problembeschreibung

=== Momentane Probleme:

* Implementierung von MinIO un dessen Verbindung zur Datenbank.

== Ziele und Features

=== Ziele der Anwendung:

* Die Anwendung soll im Zusammenspiel mit anderen SCS von MOPS eine schnelle Suche und
Bereitstellung von Lehrmateriallien bieten.

* Die GUI der Anwendung soll eine schnelle und übersichtliche Navigation ermöglichen.

* Den Studierenden sollen ohne Voreinstellungen ihre benötigten Gruppenlehrmaterialien
erreichen können

=== Features der Anwendung:

* Übersichtliches GUI

* Schneller Zugriff auf benötigte Materialien

== Dokumentationsverzeichnis

* Methodendokumentation: Die Methoden der Anwendung sind im Quellcode mti Javadocs versehen, die ihre Fiunktionalität beschreiben.

* Architekturdokumentation: Architkekturbdokumentation befindet sich im Order "documentations"