= MOPS: Materialsammlung 2

== Übersicht

Die hier implementierte Materialsammlung ist auf einer Schichtarchitektur
aufgebaut und soll den Benutzern eine schnelle, effektive und übersichtliche
Suche und angenehmen Zugriff auf ihre digitalen Lehrmaterialien erlauben.


== Problembeschreibung

=== Momentane Probleme:

- Händisches schreiben schneller SQL-Queries zum erreichen der gebrauchten Daten aus
der Datenbank.

- Verknüpfen der einzelnen Programmschichten (GUI, Geschäftslogik un Persistenz) zu einem
einheitlichen Gesamtprodukt

- Mögliche Probleme beim Abrufen von Daten anderer Anwendungsmodule.

== Ziele und Features

=== Ziele der Anwendung:

- Die Anwendung soll im Zusammenspiel mit anderen SCS von MOPS eine schnelle Suche und
Bereitstellung von Lehrmateriallien bieten.

- Die GUI der Anwendung soll eine schnelle und übersichtliche Navigation ermöglichen.

- Den Studierenden sollen ohne Voreinstellungen ihre benötigten Gruppenlehrmaterialien
erreichen können

=== Features der Anwendung:

- Übersichtliches GUI

- Schneller Zugriff auf benötigte Materialien

== Dokumentationsverzeichnis

- Architekturdokumentation: