= MOPS: Materialsammlung 2

== Übersicht

Die hier implementierte Materialsammlung ist auf einer Schichtarchitektur
aufgebaut und soll den Benutzern eine schnelle, effektive und übersichtliche
Suche und angenehmen Zugriff auf ihre digitalen Lehrmaterialien erlauben.

== Ziele und Features

=== Ziele der Anwendung:

* Die Anwendung soll im Zusammenspiel mit anderen SCS von MOPS eine schnelle Suche und
Bereitstellung von Lehrmateriallien bieten.

* Die GUI der Anwendung soll eine schnelle und übersichtliche Navigation ermöglichen.

* Den Studierenden sollen ohne Voreinstellungen ihre benötigten Gruppenlehrmaterialien
erreichen können

=== Features der Anwendung:

* Übersichtliches GUI

* Schneller Zugriff auf benötigte Materialien

* Umfangreiche Suche nach Dateien

== Dokumentationsverzeichnis

* Methodendokumentation: Die Methoden der Anwendung sind im Quellcode mti Javadocs versehen, die ihre Fiunktionalität beschreiben.

* Architekturdokumentation: Architkekturbdokumentation befindet sich im Order "documentations"

== Start der Anwendung

=== Über die IDE

    docker-compose up

* Applikation über die IDE starten.

=== Als vollständiger Dockercontainer (inkl. MySQL und MinIO)

    docker-compose -f docker-compose.demo.yml up

Im Webbrowser ist die Anwendung dann unter http://localhost:8080/material2/ zu erreichen.